### PR TITLE
Update to support Laravel 6

### PR DESCRIPTION
**Pull request by remarkusable**
This PR contains the necessary changes to support Laravel 6.

### CODE REVIEW

**Comment by remarkusable** [comment]
It's based on the version 1.0, we probably want to bump up the version?
this fixes #49

**Comment by eigan** [comment]
Thanks! :)

Could you update travis.yml and replace the php section with:
```
php:
  - 7.2
  - 7.3
```

**Comment by remarkusable** [comment]
@eigan should i remove the `hhvm` in travis.yml as well? i see it's failing.

is there a way to update the PHPUnit which Travis uses to 7.5? i think the unit test failed due to Travis uses 7.3

**Comment by eigan** [comment]
Yes, you can remove `hhvm` too. Lets drop support for it. Laravel did so in 5.3 anyway.

Looks like travis uses `7.5.16`. The `setUp` methods should now be changed to `setUp(): void`

**Comment by eigan** [comment]
Thank you for work @remarkusable! 1.1.0 have been released an includes #42 too :).

**Pull request merged**
