### PR TITLE
Implementation of Laravel Gate contract

### PR DESCRIPTION
**Pull request by gerben-van-eck**
I copied the standard Laravel implementation of it's Gate contract and made it work with Doctrine by using the parent of the (proxy) class.
When using policies, it tries to find a policy for the proxy class otherwise.

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
I'm not a big fan of copying all of the code into this package. I hope we can find a more clever way of tackling this.
Which Laravel version are you targetting this to?

**Comment by gerben-van-eck** [comment]
This was written/tested for Laravel 5.3.

I don't think it's avoidable to create/duplicate the new ServiceProvider, other than integrating it into the AclServiceProvider, which is even less pretty I think.

Alternatives I can think off would be to extend the Laravel implementation, but this would be a very fragile and anti-pattern solution, or create an interface for resolving the policy, and have it injected by the IOC system. This would require changes in both Laravel and Laravel-Doctrine.
Alternatively, the Laravel Gate could be refactored to use service contracts for possible authorization services, this would have to be discussed upstream.

**Comment by patrickbrouwers** [comment]
This problem with proxies was fixed in Laravel 5.4. Is it feasible for you to upgrade to L5.4?

**Comment by gerben-van-eck** [comment]
I see, change in:
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Access/Gate.php#L360

5.4 is no problem for me, I'll upgrade to that. Thanks.

**Pull request closed without merging**
